### ISSUE TITLE
service_unavailable 

### ISSUE THREAD

**Issue by Ruchitdifferenz** [IBM-Bluemix/openwhisk-visionapp#10]
Please provide url or how can i manage it on my server let me know.

Getting error.
{
"error": "service_unavailable",
"reason": "Service unavailable"
}

**Comment by l2fprod** [comment]
@Ruchitdifferenz 

please provide more details about what you have done and what you are looking for

**Comment by Ruchitdifferenz** [comment]
Sir , i had install this demo at my system , after selection of picture app is going to crashed getting response : 

Creating temporary image document...
Document created {
  "reason" : "Service unavailable",
  "error" : "service_unavailable"
}

**Comment by l2fprod** [comment]
Did you change the values in ServerlessAPI.swift? The error looks like you did not set the Cloudant URL as described here: https://github.com/IBM-Cloud/openwhisk-visionapp#configure-xcode

**Comment by Ruchitdifferenz** [comment]
Yes i had follow same steps as given but same error shows

**Comment by l2fprod** [comment]
@Ruchitdifferenz 

The error really points to either the Cloudant URL having something incorrect or not pointing to the right database.

1/ Can you confirm the URL you put follows the scheme https://user:password@hostname?
2/ Also make sure to pick "IAM + Legacy authentication" when creating the Cloudant database to allow basic authentication.
