### ISSUE TITLE
XCode 8 Swift 3 support

### ISSUE THREAD

**Issue by rmey** [IBM-Bluemix/openwhisk-visionapp#2]
Hello would it possible to port the App to Swift 3 please? 
Openwhisk iOS SDK is now on Swift 3.

**Comment by l2fprod** [comment]
Definitely something I want to look into. Pull request welcome :)

**Comment by rmey** [comment]
I'm not a native iOS developer I was happy to convert the project to new OpenWhisk SDK but failed with the other dependencies you have chosen. So 30+x compile error left
