### ISSUE TITLE
Manual tagging

### ISSUE THREAD

**Issue by tysun** [IBM-Bluemix/openwhisk-visionapp#4]
Hi

Does this allow the user to tag images manually so the app can learn from the user's photo library? Or can the app only tag with generic labels such as "human" if the face is not famous?

**Comment by l2fprod** [comment]
@tysun 

The app uses Watson Visual Recognition and its default labels (or classifiers):
https://www.ibm.com/watson/developercloud/visual-recognition.html

The app does not provide a way for the user to tag the images. This would be a great addition actually, and one could then teach the Watson service with custom classifiers (and enough images):
https://www.ibm.com/watson/developercloud/doc/visual-recognition/classifiers-tutorials.shtml
