### ISSUE TITLE
Does not work with latest cloudant code

### ISSUE THREAD

**Issue by shekooogames** [IBM-Bluemix/openwhisk-visionapp#6]
Looks like only REST api's are available now. Can you please update the code ?

**Comment by l2fprod** [comment]
@upwardstudios can you be more specific about the issue? Do you have a stacktrace, an error log? thank you.

**Comment by l2fprod** [comment]
I've tested the app today, deploying it to Bluemix public with OpenWhisk and Cloudant. No issue. Please reopen with more details if you still have issues.
