### ISSUE TITLE
vision-analysis.js fails with syntax errors

### ISSUE THREAD

**Issue by ahalls** [IBM-Bluemix/openwhisk-visionapp#7]
It appears that there were breaking changes in  OpenWhisk javascript sdk.  The script fails with `whisk` is not defined.   

I rewrote the main function as shown from the guidance I extracted from this [post](https://www.ibm.com/blogs/bluemix/2016/12/prepping-openwhisk-code-ga/).  But it still contains further errors.  

I'm going to try to re-write it in swift

```
function main(args) {
  if (mainImpl(args, function (err, result) {
      if (err) {
        whisk.error(err);
      } else {
        whisk.done(result, null);
      }
    })) {
    return whisk.async();
  }
}
```

**Comment by l2fprod** [comment]
@ahalls 

I suspect you did a checkout of the xcode8_swift3 branch - which should have been deleted as the code is already in master.

In master, analysis.js uses the new OpenWhisk API since a while now, with Promise: https://github.com/IBM-Bluemix/openwhisk-visionapp/blob/master/analysis.js

**Comment by ahalls** [comment]
Yes you are right.  It was all my fault.   It's cool demo app thanks for making it available.
