### ISSUE TITLE
Setup command no longer working

### ISSUE THREAD

**Issue by zachurey** [IBM-Bluemix/openwhisk-visionapp#8]
When initially setting up the project, the command
`wsk action create -p cloudantUrl [URL] -p cloudantDbName openwhisk-vision -p watsonApiKey [123] vision-analysis analysis.js` no longer works. 

Whenever I called this command I get the following error in terminal:
 `error: Invalid argument(s). File 'analysis.js' is not a valid file or it does not exist: stat analysis.js: no such file or directory
Run 'wsk --help' for usage.`

**Comment by l2fprod** [comment]
@legostarwarszach 

I can't reproduce the issue.

- make sure you have the latest CLI.
- make sure you are running from the openwhisk-visionapp directory

here is my CLI version:
```
~/dev/whisk/openwhisk-visionapp> wsk property get --cliversion
whisk CLI version	2017-07-12T20:09:05+00:00
```

**Comment by zachurey** [comment]
I was not running from the openwhisk-visionapp directory, thanks.

**Comment by zachurey** [comment]
I have a additional question. When I try to run the app I get the following error in my console:
`Document created {
  "reason" : "_reader access is required for this request",
  "error" : "unauthorized"
}`

How do I fix this?

**Comment by l2fprod** [comment]
@legostarwarszach 

Sounds like something is not correct with the Cloudant url. Make sure it is correctly set in ServerlessAPI.swift.
